spring:
  profiles:
    active: '@spring.profiles.active@'
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %replace(: %X{Request-Id} :){':  :',':'} %m%n%wEx"
  level:
    root: INFO
  tracing:
    header: 'X-Header-Trace-RequestId'

hbase:
  zookeeper:
    quorum: "local-zookeeper.default.svc.cluster.local"
  heatmap:
    table-name: "HEATMAP"
