spring:
  profiles:
    active: '@spring.profiles.active@'
  jackson:
    default-property-inclusion: NON_NULL

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %replace(: %X{Request-Id} :){':  :',':'} %m%n%wEx"
  level:
    root: INFO
  tracing:
    header: 'X-Header-Trace-RequestId'
