hbase:
  zookeeper:
    quorum: null
  heatmap:
    table-name: "HEATMAP"
    coprocessor: "com.github.vitalibo.heatmap.hbase.HeatmapAggregationRegionCoprocessor"
    column-families:
      - "DATA"
      - "META"

spark:
  config: null

job:
  word-count:
    source:
      path: null
    sing:
      path: null
