hbase:
  zookeeper:
    quorum: "local-zookeeper.default.svc.cluster.local"

spark:
  app: "Heatmap Loader"
  master: "local[*]"
  config:
    "spark.shuffle.service.enabled": "false"

job:
  word-count:
    source:
      path: "input.json"
    sink:
      path: "output"
