apiVersion: v2
name: local
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: hbase
    version: 0.1.6
    repository: "https://gradiant.github.io/bigdata-charts/"
