replicaCount: 1

image:
  repository: "heatmap-api"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: { }
  name: ""

podAnnotations: { }

podSecurityContext: { }

securityContext: { }
service:
  type: ClusterIP
  port: 8080

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: { }
tolerations: [ ]
affinity: { }

spark:
  enabled: false
  image:
    repository: "heatmap-loader"
    pullPolicy: IfNotPresent
    tag: ""
  container:
    args:
      - "generate"
      - "perlin_noise"

hbase:
  image:
    repository: "heatmap-hbase"
    pullPolicy: IfNotPresent
  prometheus:
    exporter:
      enabled: false

  hdfs:
    enabled: true
    conf:
      hdfsSite:
        dfs.replication: 1
    dataNode:
      replicas: 1
      pdbMinAvailable: 1
    persistence:
      nameNode:
        enabled: true
      dataNode:
        enabled: true
    prometheus:
      exporter:
        enabled: false
