region                  = "us-west-2"
namespace               = "vb"
environment             = "dev"
name                    = "dist-heatmap-srv"
bucket                  = "sandbox-us-west-2"
emr_release_label       = "emr-6.5.0"
vpc_id                  = "vpc-f1c2of95"
terraform_backend       = "terraform-backend-us-west-2"
key_name                = "private_key"
emr_allowed_cidr_blocks = ["0.0.0.0/0"]
public_subnets          = ["subnet-cae01de1", "subnet-d98a2b11"]
private_subnets         = ["subnet-018a31d6", "subnet-56cae991"]
image_repository_name   = "heatmap-api"
master_instance_type    = "m4.large"
master_bid_price        = 0.04
master_ebs_size         = 32
master_ebs_type         = "gp2"
core_instance_type      = "m4.large"
core_instance_count     = 3
core_bid_price          = 0.04
core_ebs_size           = 64
core_ebs_type           = "gp2"
tags                    = {
  Project = "Distributed Heatmap Service"
  Owner   = "Vitaliy Boyarsky"
}
